### ISSUE TITLE
Takes focus from selected text fields when page finishes loading

### ISSUE THREAD

**Issue by billstanden** [patrickshox/Keys#18]
I've noticed keys has a persistent issue on pages where text fields are selectable before the page completely finishes loading.

When this happens, you can start typing in the text field only for Keys to take focus away from that field at the completion of the load.  The pages behave as expected with the Keys extension disabled.

**Comment by patrickshox** [comment]
Thanks for leaving an issue. Actually, that _is_ the intended behavior. I give the focus to Keys when the page loads so that users don't have to click out of an autofocused field when pages load.
https://github.com/patrickshox/Keys/blob/46e24afc75da72bb09db4f9f4a78686378d02e21/Keys%20Extension/Keys.js#L26-L33
The way you phrased it, I can see how it might be annoying, so I've added it as an option in the main app. 

<img width="561" alt="Screen Shot 2020-03-19 at 7 27 57 AM" src="https://user-images.githubusercontent.com/47332449/77065061-f8f52080-69b6-11ea-806f-273dc4fcdc87.png">

This will be available in the next version of the app, which I'll probably publish soon.
