### ISSUE TITLE
Problems with the German localization

### ISSUE THREAD

**Issue by melgu** [patrickshox/Keys#23]
First of all, I want to thank you for this tool. It's quite helpful.

But the German localization is so bad that it would probably be better to just use English.

As an example, I don't know what `Konzentrieren Sie sich auf das Laden der Seite` heißen soll.
Why should I focus myself on loading the page?

In pretty much every label, there's a grammatical error.
Also, for some reason the window label is `Tasten` instead of the app name `Keys`.

I'd be willing to update the German translation at a later point, but for now, it would be much better to default to the English labels.

**Comment by patrickshox** [comment]
Thanks for bringing this to my attention. 🙂 Since I just used Google Translate for the German translations, whereas English is my native language, I suspected bilingual people would prefer the English. But I think many German speakers aren’t bilingual and depend on those translations. For that reason, I’d prefer to keep the (flawed) German.

**Comment by melgu** [comment]
Thanks for your reply. I understand that.
I can recommend [DeepL](DeepL.com). It’s better than Google in that regard.
If it is not too much work, could you implement a setting to choose the language?
