### ISSUE TITLE
Open in new background tab

### ISSUE THREAD

**Issue by manspeterson** [patrickshox/Keys#8]
First of all, thank you for a great extension. It truly has improved my browsing.

However, I would love to be able to somehow tell Keys to open a new tab in the background and then go back into hiding. Maybe using a modifier key? Cmd-clicking is the default for this behavior, but I see why that wouldn't work in this case. However, using shift as a modifier while pressing the last letter in a key could to the job?

**Comment by mentalisttraceur** [comment]
I presume you (the developer(s)) are familiar with the Vim-like browser extensions for various browsers, all of which implement something like this - and they indeed tend to do this with either

1. a modifier key (`f` follows a link, `F` follows a link in a new tab),
2. a different key (`f` follows a link, `b` follows a link in a new background tab), or
3. a key sequence (`f` follows a link, `;f` follows a link in a new tab, `;b` follows a link in a new background tab).

I don't think either of these is hard to explain to users. Users aren't stupid, and they are willing or even eager to learn if you're teaching them something intuitive and memorable - something that fits with their mental model.

Anyway, this is a pretty fundamental, essential part of browsing. Probably at least half of my link-clicking actions for the last several years have been to open things in a new foreground tab or a new background tab. You could argue this is an unhealthy browsing pattern which leaves me with a gradually growing backlog of tabs I never get around to reading and consumes my time and productivity with the ones that I do get around to reading, and that a more ideal, focused me would not feel the need to have this feature so much.

But as it stands now, I feel it often, and I feel it prominently. I don't really mind hitting `Cmd+L Cmd+Enter` or `Cmd+L Cmd+Shift+Enter` or `Cmd+K` (that last one I had to set up to `Window->Duplicate Tab` in System Preferences -> Keyboard -> Shortcuts -> App Shortcuts) and then hitting `G`, but it feels inefficient, requires multiple key chords instead of just typing, and doesn't always work smoothly on web pages which lose essential state in the duplicated tab.

I really, really recommend looking at what is implemented in the Vim-like browsers (Qutebrowser, Vieb) and the Vim-like browser extensions (Tridactyl, Vimium, and so on). They ***all*** implement separate "open/click" vs "open in a new tab" operations.

**Comment by patrickshox** [comment]
Point taken. The next version of Keys will include the ability to use the command key with the activation key to open in a background tab. I still doubt many people want this, so this functionality will be opt-in.
<img width="561" alt="Screen Shot 2020-09-23 at 4 56 13 PM" src="https://user-images.githubusercontent.com/47332449/94073413-6ef29e00-fdc5-11ea-8752-cf24e6066577.png">
Commit 5df823e closes #8.

**Comment by manspeterson** [comment]
That's amazing @patrickshox. Thank you so much for putting in the effort into something you're not convinced about. And for all your hard work!

**Comment by mentalisttraceur** [comment]
Awesome! Thank you!

**Comment by al3xandru** [comment]
@patrickshox firstly thanks for considering and implementing this feature.

I don't think there are any unbound `Cmd` shortcuts in Safari and thus finding the one that I'll miss the least will be challenging. Would it be possible to make this work with `Shift` instead of `Cmd` to avoid such conflicts?
